- name: Create SSL certificates for standalone server
  hosts: all
  become: true
  vars_files:
    - ../host_vars/secrets.yml
  vars:
    letsencrypt_dir: "/etc/letsencrypt/live/{{ domain_name }}"
    cert_file: "{{ letsencrypt_dir }}/fullchain.pem"

  pre_tasks:
    - name: Check if Certbot SNAP is installed
      ansible.builtin.command: snap list certbot
      register: certbot_snap_check
      changed_when: false
      failed_when: false

    - name: Exit playbook if Certbot is not installed
      ansible.builtin.meta: end_play
      when: certbot_snap_check.rc != 0

  tasks:
    - name: Check if certificates already exist
      ansible.builtin.stat:
        path: "{{ cert_file }}"
      register: cert_files

    - name: Generate SSL certificates using Certbot for standalone server
      ansible.builtin.command: >
        certbot certonly
        --standalone
        --email {{ certbot_email }}
        -d {{ domain_name }}
        -d '*.{{ domain_name }}'
        --agree-tos
        --non-interactive
      args:
        creates: "{{ cert_file }}"
      when: not cert_files.stat.exists

    - name: Display SSL certificates information
      ansible.builtin.command: certbot certificates
      register: cert_info
      changed_when: false

    - name: Show SSL certificates information
      ansible.builtin.debug:
        var: cert_info.stdout_lines
